### ISSUE TITLE
Plan 2023.02.15: Dashboards at Ontology Summit 2023

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#343]
[Summit plan](https://oboacademy.github.io/obook/courses/ontology-summit-2023/)

## Current schedule

Remember everyone to leave 3 -5 minutes for questions in each unit

09:05am: The problem of encouraging and monitoring ontology standardisation (@matentzn, @cthoyt)
09:15am: Overview of the OBO Dashboard: Standardising metadata across OBO Foundry ontologies (@matentzn)
09:30am: Other dashboards for standardising metadata ([oquat](https://cthoyt.com/oquat/), [versions](https://psiotwo.github.io/ontology-version-extractor/output.html)) (@cthoyt)
09:37am: Dashboards for measuring social workflows ([OBO health](https://cthoyt.com/obo-community-health/)) (@cthoyt)
09:45am: Using the OBO Dashboard Kit to create your own, customised Dashboard (@anitacaron)

## Tutors

@cthoyt  
@matentzn
@anitacaron

## Todos

- [X] Draft [slide deck](https://docs.google.com/presentation/d/1oKxBzSCZGuFlIhw6jAXw00xgEGs7KgmaVR54NEdPprw/edit#slide=id.g20803e73efb_0_85)
- [ ] All taught units have associated documentation pages
- [ ] Schedule is finished

**Comment by matentzn** [comment]
@cthoyt I was thinking of focussing on general OBO metadata standardisation in the first 15 minutes, with a focus on vision, rather than focussing too much on specific dashboards. We then introduce the Dashboards as means to track progress and increase transparency.

**Comment by cthoyt** [comment]
Agreed, it would be best for us to reflect on the community needs, what kinds of standardization efforts are ongoing, how they’re important, how we prioritize, etc. the dashboards are just the logical next step “here’s how we automate tracking this in an objective way and communicating it over time”

**Comment by matentzn** [comment]
Finished, very nice job @anitacaron and @cthoyt!
